export const orderStepTypes = {
  ORDER_REQUESTED: 'ORDER_REQUESTED',
  ORDER_ACCEPTED: 'ORDER_ACCEPTED',
  ORDER_BEING_PREPARED: 'ORDER_BEING_PREPARED',
  ORDER_LEFT_FOR_DELIVERY: 'ORDER_LEFT_FOR_DELIVERY',
  ORDER_DELIVERED: 'ORDER_DELIVERED',
}